### ISSUE TITLE
Password support

### ISSUE THREAD

**Issue by orenk86** [aurooba/alfred-workflow-zoom-meetings#1]
Hi, nice workflow!! :)

Any chance you can add support for passwords encoded in the link? (the "pwd" query parameter).

Thanks!

**Comment by aurooba** [comment]
Glad you liked it @orenk86! Yes! I can add support this weekend. :)

**Comment by aurooba** [comment]
Hey @orenk86, you can download [today's release](https://github.com/aurooba/alfred-workflow-zoom-meetings/releases/tag/1.2.0), which supports password encoded Zoom links as well. :)

**Comment by orenk86** [comment]
Hi @aurooba , thanks a lot, but unfortunately it's not working for me :(

**Comment by aurooba** [comment]
Hmm. Do you see an error? Can you describe what happens?

**Comment by orenk86** [comment]
No error, just that if I highlight a Zoom link with a 'pwd' parameter and press the keyboard shortcut, it will still ask me for the password.
Perhaps I should try it with the 'zm' keyword?

**Comment by aurooba** [comment]
Ah! Yes, I forgot to add it to the shortcut section. It will definitely work with the `zm` keyword. I'll fix the shortcut version right away here.

**Comment by aurooba** [comment]
@orenk86 Here you go: https://github.com/aurooba/alfred-workflow-zoom-meetings/releases/tag/v1.2.1 

:)

**Comment by orenk86** [comment]
Works perfectly, thanks!
